from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),


    path('String/', views.String, name='String'),
    path('String/s1/', views.s1, name='s1'),
    path('String/s1/tests1', views.tests1, name='tests1'),
    path('String/s2/', views.s2, name='s2'),
    path('String/s2/tests2', views.tests2, name='tests2'),
    path('String/s3/', views.s3, name='s3'),
    path('String/s3/tests3', views.tests3, name='tests3'),
    path('String/s4/', views.s4, name='s4'),
    path('String/s4/tests4', views.tests4, name='tests4'),


    path('Array/', views.Array, name='Array'),
    path('Array/a1/', views.a1, name='a1'),
    path('Array/a1/testa1', views.testa1, name='testa1'),
    path('Array/a2/', views.a2, name='a2'),
    path('Array/a2/testa2', views.testa2, name='testa2'),
    path('Array/a3/', views.a3, name='a3'),
    path('Array/a3/testa3', views.testa3, name='testa3'),
    path('Array/a4/', views.a4, name='a4'),
    path('Array/a4/testa4', views.testa4, name='testa4'),
    path('Array/a5/', views.a5, name='a5'),
    path('Array/a5/testa5', views.testa5, name='testa5'),


    path('Loop/', views.Loop, name='Loop'),
    path('Loop/l1/', views.l1, name='l1'),
    path('Loop/l1/testl1', views.testl1, name='testl1'),
    path('Loop/l2/', views.l2, name='l2'),
    path('Loop/l2/testl2', views.testl2, name='testl2'),
    path('Loop/l3/', views.l3, name='l3'),
    path('Loop/l3/testl3', views.testl3, name='testl3'),
    path('Loop/l4/', views.l4, name='l4'),
    path('Loop/l4/testl4', views.testl4, name='testl4'),
    path('Loop/l5/', views.l5, name='l5'),
    path('Loop/l5/testl5', views.testl5, name='testl5'),
    path('Loop/l6/', views.l6, name='l6'),
    path('Loop/l6/testl6', views.testl6, name='testl6'),
    path('Loop/l7/', views.l7, name='l7'),
    path('Loop/l7/testl7', views.testl7, name='testl7'),
    path('Loop/l8/', views.l8, name='l8'),
    path('Loop/l8/testl8', views.testl8, name='testl8'),
    path('Loop/l9/', views.l9, name='l9'),
    path('Loop/l9/testl9', views.testl9, name='testl9'),
    path('Loop/l10/', views.l10, name='l10'),
    path('Loop/l10/testl10', views.testl10, name='testl10'),
    path('Loop/l11/', views.l11, name='l11'),
    path('Loop/l11/testl11', views.testl11, name='testl11'),
    path('Loop/l12/', views.l12, name='l12'),
    path('Loop/l12/testl12', views.testl12, name='testl12'),
    path('Loop/l13/', views.l13, name='l13'),
    path('Loop/l13/testl13', views.testl13, name='testl13'),
    path('Loop/l14/', views.l14, name='l14'),
    path('Loop/l14/testl14', views.testl14, name='testl14'),


    path('Simple/', views.Simple, name='Simple'),
    path('Simple/n1/', views.n1, name='n1'),
    path('Simple/n1/testn1', views.testn1, name='testn1'),
    path('Simple/n2/', views.n2, name='n2'),
    path('Simple/n2/testn2', views.testn2, name='testn2'),
    path('Simple/n3/', views.n3, name='n3'),
    path('Simple/n3/testn3', views.testn3, name='testn3'),
    path('Simple/n4/', views.n4, name='n4'),
    path('Simple/n4/testn4', views.testn4, name='testn4'),
    path('Simple/n5/', views.n5, name='n5'),
    path('Simple/n5/testn5', views.testn5, name='testn5'),
    path('Simple/n6/', views.n6, name='n6'),
    path('Simple/n6/testn6', views.testn6, name='testn6'),
    path('Simple/n7/', views.n7, name='n7'),
    path('Simple/n7/testn7', views.testn7, name='testn7'),
    path('Simple/n8/', views.n8, name='n8'),
    path('Simple/n8/testn8', views.testn8, name='testn8'),
    path('Simple/n9/', views.n9, name='n9'),
    path('Simple/n9/testn9', views.testn9, name='testn9'),
    path('Simple/n10/', views.n10, name='n10'),
    path('Simple/n10/testn10', views.testn10, name='testn10'),
    path('Simple/n11/', views.n11, name='n11'),
    path('Simple/n11/testn11', views.testn11, name='testn11'),
]
